// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"golayout/internal/dao"
	"golayout/internal/pkg/config"
	"golayout/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireNewServer(option ...grpc.ServerOption) (*Server, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	server := grpc.NewServer(option...)
	book := dao.NewBook()
	serviceBook := service.NewBook(book)
	services := &service.Services{
		Book: serviceBook,
	}
	serverServer, err := newServer(configConfig, server, services)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
